require("config.options")
require("config.keymaps")
require("config.lsp")
require("config.colorscheme")

require("config.plugins.blink")
require("config.plugins.formatter")
require("config.plugins.mini")
require("config.plugins.oil")
require("config.plugins.roslyn")
require("config.plugins.snacks")
require("config.plugins.treesitter")
