[settings]
animate = false
default_disable = false
focus_follows_mouse = false
mouse_follows_focus = true
mouse_hides_on_focus = false
hot_reload = true

[settings.layout]
mode = "scrolling"
window_insertion_point = "next_to_selection"

[settings.layout.scrolling]
column_width_ratio = 0.5
min_column_width_ratio = 0.3
max_column_width_ratio = 1.0
alignment = "center"
focus_navigation_style = "niri"

[settings.layout.gaps.outer]
top = 0
left = 0
bottom = 0
right = 0

[settings.layout.gaps.inner]
horizontal = 5
vertical = 5

[virtual_workspaces]
enabled = true
default_workspace_count = 9
default_workspace = 0
workspace_names = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
app_rules = [
  { app_id = "net.imput.helium", workspace = "1" },
  { app_id = "com.mitchellh.ghostty", workspace = "2" },
  { app_id = "md.obsidian", workspace = "3" },
  { app_id = "com.t3tools.t3code", workspace = "4" },
]

[keys]
"Alt + Z" = "toggle_space_activated"

"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

"Alt + Shift + H" = { move_node = "left" }
"Alt + Shift + J" = { move_node = "down" }
"Alt + Shift + K" = { move_node = "up" }
"Alt + Shift + L" = { move_node = "right" }

"Alt + Shift + Left" = "resize_window_grow"
"Alt + Shift + Right" = "resize_window_shrink"

"Alt + 1" = { switch_to_workspace = 0 }
"Alt + 2" = { switch_to_workspace = 1 }
"Alt + 3" = { switch_to_workspace = 2 }
"Alt + 4" = { switch_to_workspace = 3 }
"Alt + 5" = { switch_to_workspace = 4 }
"Alt + 6" = { switch_to_workspace = 5 }
"Alt + 7" = { switch_to_workspace = 6 }
"Alt + 8" = { switch_to_workspace = 7 }
"Alt + 9" = { switch_to_workspace = 8 }

"Alt + Shift + 1" = { move_window_to_workspace = { workspace = 0, follow = true } }
"Alt + Shift + 2" = { move_window_to_workspace = { workspace = 1, follow = true } }
"Alt + Shift + 3" = { move_window_to_workspace = { workspace = 2, follow = true } }
"Alt + Shift + 4" = { move_window_to_workspace = { workspace = 3, follow = true } }
"Alt + Shift + 5" = { move_window_to_workspace = { workspace = 4, follow = true } }
"Alt + Shift + 6" = { move_window_to_workspace = { workspace = 5, follow = true } }
"Alt + Shift + 7" = { move_window_to_workspace = { workspace = 6, follow = true } }
"Alt + Shift + 8" = { move_window_to_workspace = { workspace = 7, follow = true } }
"Alt + Shift + 9" = { move_window_to_workspace = { workspace = 8, follow = true } }

"Alt + Shift + T" = "toggle_orientation"
"Alt + Shift + F" = "toggle_window_floating"
